using System.Windows.Controls;

namespace Layla.Desktop
{
    /// <summary>
    /// Interaction logic for MainPage.xaml
    /// </summary>
    public partial class MainView : Page
    {
        public MainView()
        {
            InitializeComponent();
        }

        private void InitializeComponent()
        {
            // This method is usually auto-generated by the XAML designer.
            // If your project is missing the auto-generated file, you may need to rebuild the project,
            // ensure the .xaml file is correctly linked, or manually add this stub to avoid CS0103.
        }
    }
}
